# IMPORTS
import pygame as pg
import math
import os


# SCREEN SETTINGS
pg.init()
os.environ['SDL_VIDEO_CENTERED']='1'
INFO=pg.display.Info()
RES=WIDTH,HEIGHT= INFO.current_w, INFO.current_h
# RES = 1536, 864
FPS=60


# MAP SETTINGS
DIMENSIONS=(16 ,9)
TILE_X=WIDTH/DIMENSIONS[0]
# TILE_X=96
TILE_Y=HEIGHT/DIMENSIONS[1]
# TILE_Y=96


# PLAYER SETTINGS
PLAYER_POS=WIDTH/(TILE_X*2), HEIGHT/(TILE_Y*2)
PLAYER_ANGLE=3*math.pi/2
PLAYER_SPEED=2
PLAYER_ROT_SPEED=2


# VIEWPORT SETTINGS
FOV=math.pi/3
H_FOV=FOV/2
CASTED_RAYS=WIDTH//2
H_CASTED_RAYS=CASTED_RAYS//2
DELTA_ANGLE=FOV/CASTED_RAYS
MAX_DEPTH=20